---
name: Python Code

on: [push]

jobs:
  test:
    name: Python Code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build package
        run: make deps && make -j && make knotty ipknot
      - name: Check formatting
        run: .venv/bin/black . --check
      - name: Test binary
        run: .venv/bin/rna_analysis --help
      - name: Run unit tests
        run: .venv/bin/pytest tests -v
